
version: '3.8'

services:
  research-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: research-made-readable
    ports:
      - "8501:8501"
    environment:
      # Environment variables - create .env file with your API key
      - ABACUSAI_API_KEY=${ABACUSAI_API_KEY}
      # Optional: Override default Streamlit configuration
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_HEADLESS=true
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      # Mount logs directory for debugging
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - research-network
    depends_on: []
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  research-network:
    driver: bridge

volumes:
  # Named volumes for data persistence (alternative to bind mounts)
  research-data:
    driver: local
  research-logs:
    driver: local
